version: 0.2
phases:
  install:
    runtime-versions:
      android: 29
      java: corretto11
#       nodejs: 14
    commands:
      - pwd
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - npm --version
      - sudo apt install nodejs
      - sudo apt install npm
#       - yarn
      - sudo apt install openjdk-8-jre openjdk-8-jdk
      - npm install -g react-native-cli
      - react-native link
      - cd android
      - pwd
      
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean
      - ./gradlew assembleRelease
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - /app/build/outputs/apk/release/*.apk
  discard-paths: yes
