version: 0.2

phases:
  install:
    runtime-versions:
      android: 29
      java: corretto8
      nodejs: 12
    commands:
      - pwd
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - npm --version
      - npm install -g react-native-cli
      - yarn
      - react-native link
      - cd android
      - pwd
      
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean
      - ./gradlew assembleRelease
# #   - ./gradlew assembleDebug
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls
      - ls app/
      - ls app/build/
      - ls app/build/outputs/
      - ls app/build/outputs/apk/
      - ls app/build/outputs/apk/release/ 
artifacts:
  #   commands:
  #     - echo running PWD command
  #     - pwd
  #     - echo running ls command
  #     - ls
  files:
    -  android/app/build/outputs/apk/release/app-release.apk
  discard-paths: yes
