version: 0.2

phases:
  install:
    runtime-versions:
      android: 29
      java: corretto8
      nodejs: 12
    commands:
      - pwd
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - npm --version
      - npm install -g react-native-cli
#       - sudo apt install nodejs
#       - sudo apt install npm
      - yarn
#       - apt install openjdk-8-jre openjdk-8-jdk

      - react-native link
      - cd android
      - pwd
      
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean
      - ./gradlew assembleRelease
#       - ./gradlew assembleDebug
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
#   commands:
#     - echo running PWD command
#     - pwd
#     - echo running ls command
#     - ls
  files:
#     - ./app/build/outputs/apk/app-debug.apk
#       - codepipeline-ap-south-1-339849233137/pipeline-four/SourceArti/app-debug.apk
#   discard-paths: yes
